### ISSUE TITLE
CPLEX full license not working

### ISSUE THREAD

**Issue by rcraney92** [BlockResearchGroup/WS_Taubman#1]
When trying to run the brick equilibrium script for more than 25 bricks, we are given an error explaining that CPLEX community is restricted. We have installed the CPLEX student version (which should be unrestricted), however the same error pops up on the script. When we uninstalled the CPLEX community version, it broke the script and I had to recreate the virtual environment.

Thanks,
Ryan

**Comment by brgcode** [comment]
hi,

that sounds a bit as if the cplex installation is not aware of your license.
can you elaborate a bit on the steps you took to get it installed/activated?
could you also post a bit more info about the error?

thanks

**Comment by rcraney92** [comment]
I am new to COMPAS and still learning my way through Python, but I'll do my best to describe the installation/activation process thus far.
Steps taken:
1. Installed COMPAS using process described in the WS_Taubman repository
2. Registered and installed CPLEX Optimization Studio through IBM student page.
3. Installed docplex into environment using conda (https://anaconda.org/IBMDecisionOptimization/docplex)
4. Tried uninstall the cplex (restricted-version) library installed via the WS_Taubman process (noted above). This broke compas and I had to reset the environment.
5. Tried tracing the error through the compas source code, but was unable to find a fix.

**Comment by rcraney92** [comment]
Regarding the original error message, unfortunately I did not take a screenshot. And now when I go to replicate it, I'm getting a different error "ImportError: DLL load failed: The specified module could not be found."
This new error seems to be an issue with the reinstalling of compas, and resetting it again has not fixed the error. Attached is the full text of the error.
![Error_191022](https://user-images.githubusercontent.com/56800058/67327198-2c518300-f4dd-11e9-829a-595a2fca9b38.png)

**Comment by brgcode** [comment]
hi,

the latest error is easily fixed. there is a compatibility problem between the latest version of `matplotlib` and `pillow`. just do the following from the Anaconda Prompt (within the correct environment):

```bash
conda install matplotlib=3.0
```

and the problem should go away...

**Comment by brgcode** [comment]
about the installation of the academic edition of CPLEX.

* don't install `docplex`. that is basically an interface to `cplex` that can switch between solving problems locally or in the cloud. when you solve them locally it will simply use `cplex` in the background.
* follow the instructions [here](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.8.0/ilog.odms.cplex.help/CPLEX/GettingStarted/topics/set_up/Python_setup.html) to properly install the academic license solver. it is not sufficient to just install using `conda install cplex` because this will always give you the community version. according to [this discussion](https://www.ibm.com/developerworks/community/forums/html/topic?id=b03f7367-e574-4dde-9a2d-5a4c7e95aed9) you can install the academic version "over" the community version. no need to uninstall it (but if you already did that is also fine)...

let me know if that didn't work.

**Comment by rcraney92** [comment]
Thank you, everything seems to be running smoothly now.
